// <auto-generated />
using IMS_Web.DbEntity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IMS_Web.Migrations
{
    [DbContext(typeof(ComponentContext))]
    partial class ComponentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("IMS_Web.Model.tbl_components", b =>
                {
                    b.Property<int>("component_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("componenet_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("component_id");

                    b.ToTable("components");
                });

            modelBuilder.Entity("IMS_Web.Model.tbl_depended", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("component_id")
                        .HasColumnType("int");

                    b.Property<int>("depended_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("depended");
                });

            modelBuilder.Entity("IMS_Web.Model.tbl_schema", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("component_id")
                        .HasColumnType("int");

                    b.Property<int>("quantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("schema");
                });
#pragma warning restore 612, 618
        }
    }
}
